// <auto-generated />
using System;
using IOrder.infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOrder.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628034014_FixCategoryRelationships")]
    partial class FixCategoryRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.OpeningHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeOnly>("CloseHour")
                        .HasColumnType("time(6)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenHour")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("OpeningHour");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentPromotionalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Customizable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.PromotionPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FinalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InitialTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.StoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StoreCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("125772b6-55fd-441d-95b2-b418feeb49ef"),
                            Active = true,
                            IconUrl = "",
                            Name = "Lanches"
                        },
                        new
                        {
                            Id = new Guid("36b1ab6f-dcd2-41f2-85fa-f546ef171304"),
                            Active = true,
                            IconUrl = "",
                            Name = "Pizzaria"
                        },
                        new
                        {
                            Id = new Guid("c9e52d68-b51c-48bf-adc3-fe2d19487205"),
                            Active = true,
                            IconUrl = "",
                            Name = "Açaí"
                        },
                        new
                        {
                            Id = new Guid("d18a4be9-a6d5-4bc1-bfef-0b85c324ade1"),
                            Active = true,
                            IconUrl = "",
                            Name = "Japonês"
                        },
                        new
                        {
                            Id = new Guid("99f1b14a-142c-4066-9abc-99fc0325f47a"),
                            Active = true,
                            IconUrl = "",
                            Name = "Brasileira"
                        },
                        new
                        {
                            Id = new Guid("80cd6d01-2113-45ac-97ad-96a2271b5e65"),
                            Active = true,
                            IconUrl = "",
                            Name = "Doces e Bolos"
                        },
                        new
                        {
                            Id = new Guid("53dd31ea-ce9a-412f-9bcd-9135fe7d6d9b"),
                            Active = true,
                            IconUrl = "",
                            Name = "Farmácia"
                        },
                        new
                        {
                            Id = new Guid("5b669945-c452-402a-8321-3557292b31e5"),
                            Active = true,
                            IconUrl = "",
                            Name = "Mercado"
                        },
                        new
                        {
                            Id = new Guid("6d335be8-7d81-446e-bae0-8edb561c70a5"),
                            Active = true,
                            IconUrl = "",
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = new Guid("7ec4e320-13fa-4b2d-9211-e903dae2577f"),
                            Active = true,
                            IconUrl = "",
                            Name = "Saudável"
                        });
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.OpeningHour", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany("OpeningHours")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.PromotionPrice", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.StoreCategory", "Category")
                        .WithMany("Stores")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IOrder.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.Navigation("OpeningHours");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.StoreCategory", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
