// <auto-generated />
using System;
using IOrder.infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOrder.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627035936_AddStoreCategories")]
    partial class AddStoreCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StoreId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId1");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.OpeningHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeOnly>("CloseHour")
                        .HasColumnType("time(6)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenHour")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("OpeningHour");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentPromotionalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Customizable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.PromotionPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FinalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InitialTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.StoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StoreCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a796b547-e119-4b5c-b5d8-72ac98230f52"),
                            Active = true,
                            IconUrl = "",
                            Name = "Lanches"
                        },
                        new
                        {
                            Id = new Guid("9534e443-062c-4d52-a5c3-91ba524e164b"),
                            Active = true,
                            IconUrl = "",
                            Name = "Pizzaria"
                        },
                        new
                        {
                            Id = new Guid("2ded531b-5eeb-4d69-9f7a-90895b315ec1"),
                            Active = true,
                            IconUrl = "",
                            Name = "Açaí"
                        },
                        new
                        {
                            Id = new Guid("1dee1a76-b7d5-429c-9250-70a735dcc297"),
                            Active = true,
                            IconUrl = "",
                            Name = "Japonês"
                        },
                        new
                        {
                            Id = new Guid("72c90639-625d-498c-a510-47b75494cf2b"),
                            Active = true,
                            IconUrl = "",
                            Name = "Brasileira"
                        },
                        new
                        {
                            Id = new Guid("34c46d06-4521-4959-9ff3-7a2a408ea2d9"),
                            Active = true,
                            IconUrl = "",
                            Name = "Doces e Bolos"
                        },
                        new
                        {
                            Id = new Guid("1e88ad1a-c9e8-4d86-8e0b-3da38d55650e"),
                            Active = true,
                            IconUrl = "",
                            Name = "Farmácia"
                        },
                        new
                        {
                            Id = new Guid("b0200c03-606b-4180-a682-a407998d572a"),
                            Active = true,
                            IconUrl = "",
                            Name = "Mercado"
                        },
                        new
                        {
                            Id = new Guid("f9523ef8-b571-4dac-96a2-715292afb6ea"),
                            Active = true,
                            IconUrl = "",
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = new Guid("410a6b0f-7355-4e44-8e69-82c74feed28d"),
                            Active = true,
                            IconUrl = "",
                            Name = "Saudável"
                        });
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.OpeningHour", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany("OpeningHours")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.PromotionPrice", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.StoreCategory", "Category")
                        .WithMany("Stores")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IOrder.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.Navigation("OpeningHours");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.StoreCategory", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
