// <auto-generated />
using System;
using IOrder.infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOrder.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628035129_UpdateSeedDataForOrderingApp")]
    partial class UpdateSeedDataForOrderingApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Active = true,
                            Name = "Bolos de Casamento",
                            Position = 1,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Active = true,
                            Name = "Doces Gourmet",
                            Position = 2,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Active = true,
                            Name = "Fritos na Hora",
                            Position = 1,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Active = true,
                            Name = "Tortas e Assados",
                            Position = 2,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Active = true,
                            Name = "Cestas Românticas",
                            Position = 1,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("IOrder.Domain.Entities.OpeningHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeOnly>("CloseHour")
                        .HasColumnType("time(6)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenHour")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("OpeningHour");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("CurrentPromotionalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Customizable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Active = true,
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Customizable = true,
                            Description = "Bolo com recheio a escolha e cobertura de pasta americana.",
                            ImageUrl = "https://example.com/bolo_casamento.png",
                            Name = "Bolo de Casamento 3 Andares",
                            Price = 350.00m,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000001"),
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Active = true,
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Customizable = false,
                            Description = "100 unidades de delicioso camafeu fondant com nozes.",
                            ImageUrl = "https://example.com/camafeu.png",
                            Name = "Camafeu de Nozes (Cento)",
                            Price = 180.00m,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000001"),
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Active = true,
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Customizable = false,
                            Description = "100 coxinhas de frango para festa, massa de batata.",
                            ImageUrl = "https://example.com/coxinha.png",
                            Name = "Cento de Coxinha",
                            Price = 75.00m,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000002"),
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Active = true,
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Customizable = true,
                            Description = "Empadão familiar de 2kg com bastante recheio.",
                            ImageUrl = "https://example.com/empadao.png",
                            Name = "Empadão de Frango 2kg",
                            Price = 65.00m,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000002"),
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Active = true,
                            CategoryId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Customizable = true,
                            Description = "Cesta de vime com pães, frutas, sucos, xícara decorada e um ursinho.",
                            ImageUrl = "https://example.com/cesta.png",
                            Name = "Cesta de Café da Manhã Amor",
                            Price = 220.00m,
                            StoreId = new Guid("20000000-0000-0000-0000-000000000003"),
                            UnitOfMeasure = "Unidade"
                        });
                });

            modelBuilder.Entity("IOrder.Domain.Entities.PromotionPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FinalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("InitialTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            About = "Bolos decorados e doces finos sob encomenda para o seu evento.",
                            Active = true,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ImageUrl = "https://example.com/doceria.png",
                            Name = "Doceria da Maria",
                            UserId = "auth0|maria123"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            About = "Salgados fritos e assados frescos para sua festa.",
                            Active = true,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ImageUrl = "https://example.com/salgados.png",
                            Name = "Salgados Express (Sob Encomenda)",
                            UserId = "auth0|salgados123"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            About = "Presenteie quem você ama com cestas maravilhosas personalizadas.",
                            Active = true,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ImageUrl = "https://example.com/cestas.png",
                            Name = "Cestas & Cia",
                            UserId = "auth0|cestas123"
                        });
                });

            modelBuilder.Entity("IOrder.Domain.Entities.StoreCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("StoreCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Active = true,
                            IconUrl = "",
                            Name = "Bolos Decorados"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Active = true,
                            IconUrl = "",
                            Name = "Doces Finos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Active = true,
                            IconUrl = "",
                            Name = "Salgados para Festa"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Active = true,
                            IconUrl = "",
                            Name = "Cestas de Café da Manhã"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Active = true,
                            IconUrl = "",
                            Name = "Lembrancinhas Customizadas"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Active = true,
                            IconUrl = "",
                            Name = "Marmitas Saudáveis (Pré-preparo)"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Active = true,
                            IconUrl = "",
                            Name = "Tortas Salgadas"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Active = true,
                            IconUrl = "",
                            Name = "Artesanato"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Active = true,
                            IconUrl = "",
                            Name = "Kits Festa"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Active = true,
                            IconUrl = "",
                            Name = "Bebidas Artesanais"
                        });
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.OpeningHour", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany("OpeningHours")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("IOrder.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.PromotionPrice", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.HasOne("IOrder.Domain.Entities.StoreCategory", "Category")
                        .WithMany("Stores")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IOrder.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.HasData(
                                new
                                {
                                    StoreId = new Guid("20000000-0000-0000-0000-000000000001"),
                                    City = "São Paulo",
                                    Complement = "Casa",
                                    Neighborhood = "Centro",
                                    Number = "100",
                                    State = "SP",
                                    Street = "Rua das Flores",
                                    ZipCode = "12345-001"
                                },
                                new
                                {
                                    StoreId = new Guid("20000000-0000-0000-0000-000000000002"),
                                    City = "São Paulo",
                                    Complement = "Loja 2",
                                    Neighborhood = "Bela Vista",
                                    Number = "200",
                                    State = "SP",
                                    Street = "Av. Brasil",
                                    ZipCode = "12345-002"
                                },
                                new
                                {
                                    StoreId = new Guid("20000000-0000-0000-0000-000000000003"),
                                    City = "São Paulo",
                                    Complement = "Apto 101",
                                    Neighborhood = "Jardins",
                                    Number = "300",
                                    State = "SP",
                                    Street = "Rua do Amor",
                                    ZipCode = "12345-003"
                                });
                        });

                    b.Navigation("Address");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Product", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.Store", b =>
                {
                    b.Navigation("OpeningHours");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IOrder.Domain.Entities.StoreCategory", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
